from services.skill_normalizer import normalize_skill


CATEGORY_RULES = {
    "Programming Language": {
        "c/c++",
        "php development",
        "powershell",
        "scripting",
        "python",
        "java",
        "javascript",
        "typescript",
        "c",
        "c++",
        "c#",
        "scala",
        "ruby",
        "php",
        "kotlin",
        "swift",
        "objective-c",
        "cobol",
        "groovy",
        "r",
        "perl",
    },

    "Framework / Library": {
        "firebase",
        "node.js",
        "node",
        ".net development",
        "visualforce",
        "react",
        "react native",
        "angular",
        "angularjs",
        "vue.js",
        "django",
        "flask",
        "spring framework",
        "tensorflow",
        "pytorch",
        "keras",
        "jquery",
        "redux",
        "laravel",
        "ruby on rails",
        "flutter",
        ".net",
        ".net development tools",
        ".net framework",
        "asp.net",
        "entity framework",
        "express.js",
        "hibernate",
        "linq",
        "mvc",
        "symfony",
        "sharepoint framework",
        "sass",
    },

    "Database / Data Technology": {
        "sql",
        "sql server",
        "t-sql",
        "pl/sql",
        "mysql",
        "postgresql",
        "oracle",
        "oracle database",
        "mongodb",
        "nosql",
        "database management",
        "database design",
        "database development",
        "databases",
        "dax",
        "oracle sql developer",
        "soql",
        "ssis",
        "ssrs",
        "er diagrams",
    },

    "Cloud / Infrastructure": {
        "aws",
        "aws lambda",
        "azure",
        "gcp",
        "cloud computing",
        "cloud architecture",
        "cloud networking",
        "cloud platforms",
        "cloud services",
        "docker",
        "kubernetes",
        "terraform",
        "ansible",
        "linux",
        "virtualization",
        "infrastructure management",
        "infrastructure as code",
        "infrastructure as code (iac)",
        "arm templates",
        "cloudformation",
        "ec2",
        "s3",
        "vpc",
        "openstack",
        "openshift",
        "packer",
        "nomad",
        "consul",
    },

    "Data / AI": {
        "machine learning",
        "machine learning algorithms",
        "deep learning",
        "neural networks",
        "natural language processing",
        "nlp algorithms",
        "computer vision",
        "data science",
        "data analysis",
        "data mining",
        "data modeling",
        "data visualization",
        "data processing",
        "data wrangling",
        "data cleansing",
        "data governance",
        "data warehousing",
        "ai strategy",
        "ai/ml algorithms",
        "model deployment",
        "text analysis",
        "statistical analysis",
        "statistical modeling",
        "statistics",
        "data security",
        "data collection",
        "data integration",
        "data management",
        "data quality tools",
        "data recovery",
        "data lakes",
        "data pipelines",
        "data profiling",
        "dashboards",
        "metrics",
        "reporting",
        "power bi",
        "tableau",
        "excel",
        "spark",
        "hadoop",
        "kafka",
        "elasticsearch",
        "mapreduce",
        "analytics",
        "data collection",
        "data integration",
        "data management",
        "data profiling",
        "data quality tools",
        "data recovery",
    },

    "Security": {
        "cybersecurity",
        "penetration testing",
        "ethical hacking",
        "digital forensics",
        "application security",
        "cloud security",
        "container security",
        "network security",
        "vulnerability assessment",
        "vulnerability management",
        "vulnerability scanning",
        "security analysis",
        "security auditing",
        "security management",
        "security policies",
        "security protocols",
        "secure coding",
        "cryptography",
        "encryption",
        "authentication",
        "authorization",
        "access control",
        "compliance as code",
        "continuous security",
        "dast",
        "sast",
        "owasp",
        "security",
        "security audits",
        "security automation",
        "security consulting",
        "security groups",
        "security solutions",
        "security tools",
        "security information and event management (siem)",
        "security leadership",
        "threat analysis",
        "threat detection",
        "intrusion detection",
        "ids/ips",
        "splunk enterprise security",
        "hashicorp vault",
        "secrets management",
        "falco",
        "fortify",
        "firewall management",
        "firewalls",
        "trust management",
    },

    "Testing / QA": {
        "testing",
        "unit testing",
        "test automation",
        "automation testing",
        "agile testing",
        "accessibility testing",
        "performance testing",
        "code coverage",
        "quality assurance",
        "qa processes",
        "selenium",
        "pytest",
        "junit",
        "testng",
        "coverage.py",
        "jacoco",
        "test execution",
        "test planning",
        "testing frameworks",
        "webdriver",
        "user testing",
        "validation",
        "a/b testing",
    },

    "DevOps / CI-CD": {
        "devops",
        "devops practices",
        "devsecops",
        "ci/cd",
        "ci/cd pipelines",
        "jenkins",
        "gitlab ci",
        "github actions",
        "build automation",
        "deployment automation",
        "deployment strategies",
        "release management",
        "artifact repository",
        "artifactory",
        "git",
        "github",
        "gitlab",
        "bitbucket",
        "bamboo",
        "branching strategies",
        "gerrit",
        "gradle",
        "maven",
        "jfrog cli",
        "nexus",
        "octopus deploy",
        "puppet",
        "teamcity",
        "udeploy (urbancode deploy)",
        "xl deploy",
        "version control",
        "chef",
        "chef inspec",
        "container orchestration",
        "containerization",
        "envoy",
        "istio",
        "platform engineering",
        "sre",
        "system reliability",
        "automation",
        "automation tools",
        "microservices",
        "tfs (team foundation server)",
    },

    "Design / UX": {
        "figma",
        "ui design",
        "ui/ux",
        "ui/ux design",
        "ux/ui design",
        "user experience design principles",
        "interaction design",
        "information architecture",
        "wireframing",
        "prototyping",
        "responsive design",
        "assistive technologies",
        "usability testing",
        "ui design principles",
        "ui/ux basics",
        "ui/ux principles",
        "user research",
        "visual design",
        "visual communication",
        "visual storytelling",
        "adobe creative suite",
        "graphic design",
        "maya",
    },

    "Business / Management": {
        "business analysis",
        "business intelligence",
        "project management",
        "program management",
        "digital strategy",
        "innovation",
        "technical sales",
        "training",
        "portfolio management",
        "product management",
        "change management",
        "process improvement",
        "requirements gathering",
        "planning",
        "leadership",
        "team leadership",
        "team management",
        "stakeholder management",
        "business acumen",
        "business intelligence tools",
        "business process analysis",
        "business process improvement",
        "business systems",
        "client management",
        "customer engagement",
        "customer relationship management",
        "customer service",
        "product knowledge",
        "roadmap planning",
        "strategic planning",
        "technology strategy",
        "technology solutions",
        "technology adoption",
        "technology consulting",
        "it consulting",
        "it management",
        "it program management",
        "it strategy",
        "agile methodologies",
        "kanban",
        "scrum",
        "team facilitation",
    },

    "Soft Skill": {
        "communication",
        "collaboration",
        "coordination",
        "problem solving",
        "mentoring",
        "learning agility",
    },

    "Mobile Development": {
        "android sdk",
        "android studio",
        "ios",
        "ios sdk",
        "ios/android sdks",
        "mobile app development",
        "mobile development",
        "mobile security",
        "xcode",
    },

    "API / Integration": {
        "soa",
        "soql",
        "api design",
        "api development",
        "rest apis",
        "restful apis",
        "restful services",
        "web api",
        "integration",
        "integration management",
        "service discovery",
        "service mesh",
        "systems integration",
    },

    "Monitoring / Observability": {
        "alerting",
        "alerting systems",
        "application performance monitoring",
        "monitoring",
        "monitoring tools",
        "network monitoring",
        "performance monitoring",
        "system monitoring",
        "appdynamics",
        "datadog",
        "grafana",
        "kibana",
        "nagios",
        "new relic",
        "prometheus",
        "splunk",
        "zabbix",
        "log management",
        "logstash",
        "fluentd",
    },

    "Web Development": {
        "web development",
        "web development fundamentals",
        "web technologies",
        "web design",
        "html",
        "html5",
        "css",
        "css3",
        "server-side programming",
        "web content management",
        "wordpress",
        "cms",
    },

    "Architecture / Design": {
        "ai architecture",
        "ai/ml architecture",
        "uml",
        "system engineering",
        "application design",
        "software architecture",
        "system architecture",
        "system design",
        "systems design",
        "design patterns",
    },

    "Hardware / Embedded": {
        "cad/cam",
        "cnc programming",
        "g-code",
        "machining",
        "manufacturing processes",
        "toolpath optimization",
        "actuators",
        "cabling",
        "circuit design",
        "embedded c",
        "embedded systems",
        "firmware development",
        "hardware design",
        "hardware interfaces",
        "hardware management",
        "microcontrollers",
        "microprocessors",
        "pcb design",
        "sensor technology",
        "sensors",
        "control systems",
        "hardware/software",
    },

    "Networking": {
        "lan/wan",
        "network design",
        "network operations",
        "network protocols",
        "network reliability",
        "networking",
        "networking hardware",
        "networking protocols",
        "networking technologies",
        "routing",
        "subnets",
        "switching",
        "tcp/ip",
        "vpn",
        "communication protocols",
        "cisco",
    },

    "Animation / Multimedia": {
        "2d animation",
        "2d/3d animation",
        "3d animation",
        "3d modeling",
        "animation",
        "animation direction",
        "animation software",
        "art direction",
        "audio production",
        "blender",
        "character design",
        "character setup",
        "cinematography",
        "color correction",
        "compositing",
        "drawing",
        "film/animation",
        "forensic animation",
        "illustration",
        "image manipulation",
        "layout",
        "motion graphics",
        "multimedia design",
        "rigging",
        "storyboarding",
        "texturing",
        "technical animation",
        "video production",
        "visual effects",
        "visual effects supervision",
        "game design",
        "game development principles",
    },

    "IT Operations / Administration": {
        "account management",
        "active directory",
        "backup and recovery",
        "configuration management",
        "incident management",
        "incident response",
        "it support",
        "system administration",
        "systems administration",
        "troubleshooting",
        "iam systems",
        "identity and access management",
        "linux administration",
        "linux servers",
        "linux/windows servers",
        "unix administration",
        "windows server",
        "windows server administration",
        "user management",
        "information management",
    },

    "Software Engineering": {
        "application development",
        "algorithm design",
        "algorithms",
        "build tools",
        "code quality",
        "code review",
        "dependency management",
        "debugging",
        "development",
        "framework development",
        "frameworks",
        "programming",
        "programming languages",
        "software design",
        "software development",
        "software development lifecycle (sdlc)",
        "static code analysis",
        "sonarqube",
        "scalability",
    },

    "AI / Advanced Analytics": {
        "big data architecture",
        "performance analysis",
        "performance optimization",
        "performance tuning",
        "modeling",
    },

    "Data Engineering": {
        "data collection",
        "data integration",
        "data management",
        "data quality tools",
        "data recovery",
        "etl",
        "etl processes",
        "data profiling",
        "data structures",
    },

    "Enterprise / Business Systems": {
        "erp systems",
        "microsoft dynamics",
        "sap modules",
        "salesforce",
        "salesforce administration",
        "sharepoint",
        "migration tools",
        "system migration",
        "atlassian suite",
        "confluence",
        "jira",
        "anypoint platform",
        "mulesoft",
        "apex",
        "lightning",
        "soql",
        "e-commerce platforms",
        "payment gateways",
        "bpmn",
    },

    "IT Service Management": {
        "itil",
        "administrative support",
        "documentation",
        "implementation management",
        "workflow configuration",
        "technical operations",
        "technical support",
        "technical expertise",
    },

    "Marketing / SEO": {
        "seo",
        "seo strategy",
        "keyword research",
        "link building",
        "off-page optimization",
        "on-page optimization",
        "web analytics tools",
        "content creation",
        "content management",
        "content marketing",
        "content optimization",
        "content strategy",
    },

    "Finance / Business": {
        "budgeting",
        "financial analysis",
        "investment management",
        "market analysis",
        "sales",
        "sales leadership",
        "sales strategy",
        "inventory management",
    },

    "Research / Analytics": {
        "research and development",
        "research management",
        "research methodologies",
        "research methods",
        "scientific writing",
        "intelligence gathering",
        "publications",
        "storytelling",
    },

    "Game Development": {
        "game engines",
        "unity",
        "unity3d engine",
        "unreal engine",
        "vr development",
    },

    "GIS / Geospatial": {
        "cartography",
        "gis software",
        "spatial analysis",
    },

    "Robotics / Control Systems": {
        "robotics",
        "ros",
        "rtos",
        "iot platforms",
        "simulation",
    },

    "Mainframe / Legacy Systems": {
        "mainframe systems",
        "jcl",
        "j2ee",
        "vsam",
    },

    "Compliance / Governance": {
        "ada compliance",
        "compliance",
        "it auditing",
        "risk assessment",
        "risk management",
        "legal compliance",
        "legal expertise",
        "notary",
        "wcag",
    },

    "Blockchain / Web3": {
        "blockchain",
        "cryptocurrency",
        "distributed ledger",
        "ethereum",
        "consensus algorithms",
        "smart contracts",
        "solidity",
        "web3",
    },
}


def classify_skill(skill):
    """
    Classify a canonical skill using explicit rules.

    Returns:
        category name or "Other / Review"
    """

    skill = normalize_skill(skill)

    if not skill:
        return "Other / Review"

    matched_categories = [
        category
        for category, skills in CATEGORY_RULES.items()
        if skill in skills
    ]

    # Multiple category matches indicate an ambiguous rule.
    if len(matched_categories) > 1:
        return "Other / Review"

    if len(matched_categories) == 1:
        return matched_categories[0]

    return "Other / Review"